basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: gsemir0418@gmail.com
    name: GSemir
    url: http://gsemir0418.github.com/
  description: 记账应用接口文档
  title: 记账
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 测试服务是否启动
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: 测试服务是否启动
      tags:
      - Ping
  /validation_codes:
    post:
      consumes:
      - application/json
      description: 生成验证码，发送至用户邮箱
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: 发送验证码到用户邮箱
      tags:
      - ValidationCode
securityDefinitions:
  BasicAuth(JWT):
    type: basic
swagger: "2.0"
