basePath: /
definitions:
  api.CreateItemResponse:
    properties:
      resource:
        $ref: '#/definitions/queries.Item'
    type: object
  api.GetMeResponse:
    properties:
      resource:
        $ref: '#/definitions/queries.User'
    type: object
  queries.Item:
    properties:
      amount:
        type: integer
      created_at:
        type: string
      happened_at:
        type: string
      id:
        type: integer
      kind:
        $ref: '#/definitions/queries.Kind'
      tag_ids:
        items:
          type: integer
        type: array
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  queries.Kind:
    enum:
    - expenses
    - in_come
    type: string
    x-enum-varnames:
    - KindExpenses
    - KindInCome
  queries.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: gsemir0418@gmail.com
    name: GSemir
    url: http://gsemir0418.github.com/
  description: 记账应用接口文档
  title: 记账
paths:
  /api/v1/items:
    post:
      consumes:
      - application/json
      parameters:
      - description: 金额（单位：分）
        example: 100
        in: body
        name: amount
        required: true
        schema:
          type: integer
      - description: 类型
        example: expenses
        in: body
        name: kind
        required: true
        schema:
          type: string
      - description: 发生时间
        example: "2023-09-26T00:00:00Z"
        in: body
        name: happened_at
        required: true
        schema:
          type: string
      - description: 标签ID列表
        example: '[1,2,3]'
        in: body
        name: tag_ids
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CreateItemResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: 创建账目
  /api/v1/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GetMeResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 获取当前登录用户
  /ping:
    get:
      consumes:
      - application/json
      description: 如果返回 200，说明服务正常运行
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: 服务健康度
securityDefinitions:
  BasicAuth(JWT):
    type: basic
swagger: "2.0"
